import { Car, CarCategory } from "./types";

export const CAR_FLEET: Car[] = [
  {
    id: "1",
    name: "Toyota Alphard",
    category: CarCategory.LUXURY,
    pricePerDay: 950,
    priceTransfer: 350,
    seats: 7,
    image: "/car-rental-images/alpharp.jpeg",
    gallery: ["/car-rental-images/alpharp.jpeg"],
    features: [
      "VIP Captain Seats",
      "Dual Power Doors",
      "Premium Leather Interior",
      "Privacy Glass",
    ],
  },
  {
    id: "2",
    name: "Toyota Vellfire",
    category: CarCategory.LUXURY,
    pricePerDay: 900,
    priceTransfer: 350,
    seats: 7,
    image: "/car-rental-images/vellfire.jpeg",
    gallery: ["/car-rental-images/vellfire.jpeg"],
    features: [
      "Z Premier Grade",
      "Spacious Interior",
      "Advanced Safety",
      "Moonroof",
    ],
  },
  {
    id: "3",
    name: "Mercedes-Benz",
    category: CarCategory.LUXURY,
    pricePerDay: 1200,
    priceTransfer: 500,
    seats: 5,
    image: "/car-rental-images/merc.jpeg",
    gallery: ["/car-rental-images/merc.jpeg"],
    features: [
      "Business Class Comfort",
      "Ambient Lighting",
      "Burmester Sound",
      "Executive Rear Seats",
    ],
  },
  {
    id: "4",
    name: "Hyundai Staria",
    category: CarCategory.MPV,
    pricePerDay: 850,
    priceTransfer: 300,
    seats: 7,
    image: "/car-rental-images/hyundai.jpeg",
    gallery: ["/car-rental-images/hyundai.jpeg"],
    features: [
      "Futuristic Design",
      "Huge Window Views",
      "Premium Lounge Seats",
      "Advanced Safety Tech",
    ],
  },
  {
    id: "5",
    name: "Toyota Innova",
    category: CarCategory.MPV,
    pricePerDay: 450,
    priceTransfer: 180,
    seats: 7,
    image: "/car-rental-images/Aruz.jpeg",
    gallery: ["/car-rental-images/Aruz.jpeg"],
    features: [
      "Family Favorite",
      "Robust Performance",
      "Spacious Cargo Space",
      "Excellent AC",
    ],
  },
  // {
  //   id: '6',
  //   name: 'Perodua Aruz',
  //   category: CarCategory.SUV,
  //   pricePerDay: 250,
  //   priceTransfer: 150,
  //   seats: 7,
  //   image: '/car-rental-images/Aruz.jpeg',
  //   gallery: ['/car-rental-images/Aruz.jpeg'],
  //   features: ['High Ground Clearance', 'Smart Entry', '7 Seater SUV', 'Fuel Efficient'],
  // },
  // {
  //   id: '7',
  //   name: 'Perodua Alza',
  //   category: CarCategory.MPV,
  //   pricePerDay: 250,
  //   priceTransfer: 130,
  //   seats: 7,
  //   image: '/car-rental-images/WhatsApp Image 2026-01-11 at 8.08.29 AM.jpeg',
  //   gallery: [
  //     '/car-rental-images/WhatsApp Image 2026-01-11 at 8.08.29 AM.jpeg',
  //   ],
  //   features: ['Compact MPV', 'Modern Multimedia', 'Versatile Seating', 'Fuel Efficient'],
  // },
  {
    id: "8",
    name: "Perodua Bezza",
    category: CarCategory.ECONOMY,
    pricePerDay: 150,
    priceTransfer: 90,
    seats: 4,
    image: "/car-rental-images/bezza.jpeg",
    gallery: ["/car-rental-images/bezza.jpeg"],
    features: [
      "Best Economy Sedan",
      "Huge Boot Space",
      "Exceptional Fuel Economy",
      "Smooth for City",
    ],
  },
  {
    id: "9",
    name: "Toyota Vios",
    category: CarCategory.SEDAN,
    pricePerDay: 200,
    priceTransfer: 120,
    seats: 5,
    image: "/car-rental-images/vios.jpeg",
    gallery: ["/car-rental-images/vios.jpeg"],
    features: [
      "Reliable Sedan",
      "Comfortable Ride",
      "Good Fuel Economy",
      "Spacious Interior",
    ],
  },
  // {
  //   id: '10',
  //   name: 'Perodua Axia',
  //   category: CarCategory.ECONOMY,
  //   pricePerDay: 120,
  //   priceTransfer: 80,
  //   seats: 4,
  //   image: '/car-rental-images/WhatsApp Image 2026-01-11 at 8.09.37 AM.jpeg',
  //   gallery: [
  //     '/car-rental-images/WhatsApp Image 2026-01-11 at 8.09.37 AM.jpeg',
  //   ],
  //   features: ['Ultra Compact', 'Easy Parking', 'Very Economical', 'Agile Handling'],
  // },
  {
    id: "11",
    name: "Toyota Hiace",
    category: CarCategory.VAN,
    pricePerDay: 350,
    priceTransfer: 200,
    seats: 10,
    image: "/car-rental-images/hiace.jpeg",
    gallery: ["/car-rental-images/hiace.jpeg"],
    features: ["High Roof", "10 Seater", "Spacious", "Perfect for Groups"],
  },
  {
    id: "12",
    name: "Bus",
    category: CarCategory.BUS,
    pricePerDay: 1500,
    priceTransfer: 600,
    seats: 44,
    image: "/car-rental-images/bus.jpeg",
    gallery: ["/car-rental-images/bus.jpeg"],
    features: [
      "44 Seater",
      "Reclining Seats",
      "Karaoke System",
      "Luggage Compartment",
    ],
  },
];

export const TESTIMONIALS = [
  {
    name: "Johnathan Tan",
    role: "Regular Customer",
    text: "TRAVTHRU is my go-to for airport transfers. Always punctual and the cars are exceptionally clean. The Toyota Alphard is perfect for business trips.",
    rating: 5,
  },
  {
    name: "Aisyah Osman",
    role: "Family Traveler",
    text: "Booked a Toyota Innova for a trip to Genting. The driver was very careful and professional. Best service in Kuala Lumpur!",
    rating: 5,
  },
];
